import Head from 'next/head'
import { useState } from 'react';
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Cp from './cp.js'


export default function Home() {
  const [alert, setAlert] = useState({}); //default alert remove
  const alertMe = (text = '', className = 'info') => {
    setAlert({ class: className, text })
    setTimeout(() => {
      setAlert({})
    }, 3000)
  }
  return (
    <>
      <Head>
        <title>Welcome to CP Trachker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className='main'>
        <div className={'alert '+alert.class}>{alert.text}</div>
        <h1>CP TRACKER</h1>
          <div >
            <Cp alertMe={alertMe} />
          </div>
      </main>
    </>
  )
}
